### ISSUE TITLE
issues wile trying to deploy db,web,solr  in a new VM

### ISSUE THREAD

**Issue by eelucio** [FREVA-CLINT/freva-deployment#121]
I will be noting the issues I am encountering while trying to deploy microservices (not the core!) in a new VM

so far I encountered 2 while using the tui (`freva-deploy`)
- the configuration toml file is unreliable: there is no way to know which toml file is the deployment trying to execute. Everytime I load one, once the deployment has failed I encounter that certain parameters have been subrepticially modified.
 This is made evident when trying to deploy with `freva-deploy-cmd` instead where I see that the predefined configuration file is the one located in my .local e.g. `/home/$USER/miniconda3/envs/freva-deploy/share/freva/deployment/inventory.toml` (which apparently is empty...)
- the core deployment is being set up despite being unchecked. Fortunatelly I was trying to deploy all with my k number which made it impossible to reinstall the core @ levante (that was installed under the b user)
this also happens when `$ deploy-freva-cmd -c frev_instance.toml -s {web,db,freva-rest} --ask-pass -v` so I will stop here

**Comment by antarcticrainforest** [comment]
Issue one:

1) can you give more info? How can I reproduce that?

2) it's not a but it's a feature. We decided that we need version checks to make sure the system is running smoothly with all components. The deployment will check ALL versions of the components, this includes the core in Levante. If will check if the versions are up to date and if not will append the outdated services to the deployment. We've had an update of freva which hasn't made its way into the Levante yet. This is way it wants to deploy the core although you did not select it. There is somewhere a hint in the output when you run this thing

**Comment by eelucio** [comment]
Sorry, my bad.

I will run it again with verbose mode and deepen into the code to answer that question

**Comment by eelucio** [comment]
@antarcticrainforest 

while deploying the system in a new VM (e.g. xces9 with db, web, rest, all but code)

almost everything passed but the following:

```shell
TASK [vault - Inserting email secrets] *****************************************
fatal: [xces9.dkrz.de]: FAILED! => changed=true 
  cmd: |-
    /tmp/docker-or-podman exec xces-vault add-vault-secret email -s username  -s password ''
  delta: '0:00:00.282329'
  end: '2024-06-18 17:12:33.350061'
  msg: non-zero return code
  rc: 1
  start: '2024-06-18 17:12:33.067732'
  stderr: |-
    usage: /bin/add-vault-secret [-h] [--secret SECRET SECRET] path
    /bin/add-vault-secret: error: argument --secret/-s: expected 2 arguments
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>
```
I believe this has to do with
```shell
Username for mail server: 
Password for mail server: 
```
following how we used to do before (in 2023.09) I left those empty

did this change? or maybe is a totally unrelated error

**Comment by antarcticrainforest** [comment]
Did you leave those empty? In this case, sending emails from the web doesn't work. You need to set those.

**Comment by eelucio** [comment]
yes, I left them empty as remember that in the last deployment worfklow we had to set them empty (I am pretty sure).

If that is not the case what should I put? freva? my dkrz email? and the password should be the same as the Master Passowrd?

**Comment by eelucio** [comment]
aham, thanks!

**Comment by eelucio** [comment]
I succesfully deployed all services. I am trying to migrate the db from one VM to another one via

```shell
$ freva-migrate database xces9.dkrz.de xces-prod.dkrz.de  xces.cer --old-port 3306 --old-db "evaluation_system" --old-pw "XXXX" --old-user "evaluation_system" 
[11:54:49] ERROR    freva-deployment - Script returned non-zero exit status:                                                                
                    /usr/bin/mysqldump -u evaluation_system -h xces-prod.dkrz.de -p'XXXX' -P3306 --tz-utc --no-create-db    
                    evaluation_system                                                                                                       
           ERROR    freva-deployment - STDERROR:                                                                                            
                    mysqldump: [Warning] Using a password on the command line interface can be insecure.                                    
                    mysqldump: Couldn't execute 'SELECT COLUMN_NAME,                       JSON_EXTRACT(HISTOGRAM,                          
                    '$."number-of-buckets-specified"')                FROM information_schema.COLUMN_STATISTICS                WHERE        
                    SCHEMA_NAME = 'evaluation_system' AND TABLE_NAME = 'auth_group';': Unknown table 'COLUMN_STATISTICS' in                 
                    information_schema (1109)                                                                                               
                                                                                                                                            
Traceback (most recent call last):
  File "/home/etor/miniconda3/envs/freva-deploy/bin/freva-migrate", line 8, in <module>
    sys.exit(migrate())
             ^^^^^^^^^
  File "/home/etor/miniconda3/envs/freva-deploy/lib/python3.12/site-packages/freva_deployment/cli/_migrate.py", line 231, in cli
    arg.apply_func(arg)
  File "/home/etor/miniconda3/envs/freva-deploy/lib/python3.12/site-packages/freva_deployment/cli/_migrate.py", line 132, in _migrate_db
    exec_command(dump_command, stdout=f_obj)
  File "/home/etor/miniconda3/envs/freva-deploy/lib/python3.12/site-packages/freva_deployment/cli/_migrate.py", line 56, in exec_command
    raise error
  File "/home/etor/miniconda3/envs/freva-deploy/lib/python3.12/site-packages/freva_deployment/cli/_migrate.py", line 52, in exec_command
    res.check_returncode()
  File "/home/etor/miniconda3/envs/freva-deploy/lib/python3.12/subprocess.py", line 502, in check_returncode
    raise CalledProcessError(self.returncode, self.args, self.stdout,
subprocess.CalledProcessError: Command '['/usr/bin/mysqldump', '-u', 'evaluation_system', '-h', 'xces-prod.dkrz.de', 'XXXX', '-P3306', '--tz-utc', '--no-create-db', 'evaluation_system']' returned non-zero exit status 2.
```

should I create an empty table in my original DB?
maybe I should patch temporarily the code so it does not ask for it

**Comment by antarcticrainforest** [comment]
From when is the db? We have added tables in the past. You can try creating the missing tables first:

podman exec xces-db /bin/sh -c 'mariadb -u root db_name -p < /docker-entrypoint-initdb.d/002_create_tables.sql

If you don't have the 002_create_tables.sql you can try crating it from outside the container. The file is here:

https://raw.githubusercontent.com/FREVA-CLINT/freva-deployment/main/assets/share/freva/deployment/config/create_tables.sql

You'd have to set the hostname and port though.

**Comment by eelucio** [comment]
I do not remember when is the last time we updated this database, but I see `future_files` and `future_recipe` that if I am not wrong it should from around last Sept, 2023.09

I will try what you tell me, thanks

**Comment by eelucio** [comment]
apparently the `information_schema` is a database in MYSQL that provides info about the structure of other databases, tables, columns etc.

I ahve been checking that database in other VMs (regiklim and xces9) and there is no COLUMNS_STATISTICS table in any of these either

```mysql
SELECT table_schema, table_name
FROM information_schema.tables
WHERE table_name = 'COLUMN_STATISTICS';
```
is giving me an empty set in all of them. I will check why this is being triggered in the migration and how to avoid it

**Comment by eelucio** [comment]
Okey, I see it. 
we need to add `"--column-statistics=0 "`
in case there are databses with no column_statistics, that could be... many? (I have not seen that table in any of the VMs)

```python
    with NamedTemporaryFile(suffix=".sql") as temp_file:
        with open(temp_file.name, "w") as f_obj:
            f_obj.write(f"USE `{new_db_cfg['db.db']}`;\n")
            f_obj.flush()
            dump_command = (
                f"{mysqldump} -u {parser.old_user} "
                f"-h {parser.old_hostname} -p'{parser.old_pw}' "
                f"-P{parser.old_port} "
                "--tz-utc --no-create-db "
                "--column-statistics=0 "
                f"{parser.old_db}"
            )
            exec_command(dump_command, stdout=f_obj)
            _add_new_db(new_db_cfg, temp_file.name)
```
with that done the migration was seamless


according to [this](https://serverfault.com/questions/912162/mysqldump-throws-unknown-table-column-statistics-in-information-schema-1109):
> This is due to a new flag that is enabled by default in mysqldump 8. You can disable it by adding --column-statistics=0` [...]

where this comment is from 2018, go figure...

I will add a condition that tries first the dump without this extra flag, and if not with that option
