### ISSUE TITLE
Usage of a dev-version of freva-deployment

### ISSUE THREAD

**Issue by Karinon** [FREVA-CLINT/freva-deployment#55]
There is no description of how to try out a dev-version of freva-deployment. What I came up with was  installing it locally via 

```
pip install .
```

After that, the dev-version was available, but it seemed, that some template-files were missing:

```
FileNotFoundError: [Errno 2] No such file or directory: '/home/etor/.conda/envs/freva-deploy/share/freva/deployment/config/evaluation_system.conf.tmpl'
```

Going further from this error message we have downloaded the File (I forgot where I found this command, but I am relatively sure that I didn't came up with it myself):

```
wget https://raw.githubusercontent.com/FREVA-CLINT/freva/main/assets/evaluation_system.conf -O assets/share/freva/deployment/config/evaluation_system.conf.tmpl
```

And copied the whole config-Folder into the location mentioned in the error message.

**Comment by antarcticrainforest** [comment]
This error was most likely introduced when I switched from setuptools to flint as a build system. I had a custom setuptools build class that downloaded the file when installing in develop mode. I'll check if a similar approach is possible with flint. If not we will have to resort back to a makefile.
