### ISSUE TITLE
Better hints and checks in Core-Deployment

### ISSUE THREAD

**Issue by Karinon** [FREVA-CLINT/freva-deployment#58]
I tried to deploy freva on a completely fresh VM with only a yum-installed python on it. It crashed with the following error message:

```
TASK [Creating share directory with admin group] *****************************************************************************************************

fatal: [vaskebjorn2.cloud.dkrz.de]: FAILED! => {"changed": false, "msg": "There was an issue creating /opt/frevaproj as requested: [Errno 13] Permission denied: b'/opt/frevaproj'", "path": "/opt/frevaproj/freva/web"}
```

The folder in question `/opt/frevaproj` has indeed not been created prior to this execution and it was entered under `4. Directory where project configuration is stored` in the `Core`-Deployment-Section of the TUI. It seems that the system tries to create the folder as the logged in user, but can't because my k-number is not allowed to write on `/opt/`?

Following considerations:

1. Am I right, that it does not try to create those folders as `root` because it might get installed on a machine without root-permissions like levante?
2. If I am right about the first one, would it be possible to add a hint in the TUI which tells me, that the core-installation is performed as a non root user? So that I will be more aware of the fact, that the parent-
folder has to be writable?
3. Would it be possible to shift the check if the folder is usable for our current user more to the beginning of the process? It took the deployment-script 3 Minutes until I got this error message. This is way too long for such a simple check. 

All of this is also true for the folders under `5.` and `6.` in the `Core`-Deployment-Tab

**Comment by antarcticrainforest** [comment]
I added a "feature" fixing the problem in preparation for the deployment of freva at DWD. The people setting up freva do not have root privileges. I actually thought this had made its way into the main branch. But it was still only on my laptop up until now. I don't really remember how far I've gotten. I'll take care about this once the current PR (new-vault) is merged.
