### ISSUE TITLE
Stop using personal repos in deployment

### ISSUE THREAD

**Issue by Karinon** [FREVA-CLINT/freva-deployment#59]
The deployment of the core uses on one occasion a personal gitlab-repository:

https://gitlab.dkrz.de/k204230/install-kernelspec

I would prefer that we move this repository into some kind of public Freva-Space.

**Comment by antarcticrainforest** [comment]
Ok

**Comment by antarcticrainforest** [comment]
I have created pip package: https://pypi.org/project/kernel-install/.
