### ISSUE TITLE
cronjob for db backup not working (?)

### ISSUE THREAD

**Issue by eelucio** [FREVA-CLINT/freva-deployment#70]
While showing the inner-working of freva components to Mo and Manuel we realised that neither xces nor regiklim db containers have been backing up the db since (I pressume, the release of) Sept 2023.
When entering the db docker @ xces I had to install cron and start it. 
```
apt-get install cron
service cron start
```
and add a new entry to the crontab 

At this moment I am unable to pintpoint what is failing in the [playbook](
https://github.com/FREVA-CLINT/freva-deployment/blob/main/assets/share/freva/deployment/playbooks/db-server-playbook.yml) and I cannot propose any change, unfortunately.

**Comment by antarcticrainforest** [comment]
The python version on the systems seems to be older than I thought. 

/usr/local/bin/docker-or-podman exec regiklim-ces-db bash /usr/local/bin/daily_backup
Traceback (most recent call last):
  File "/usr/local/bin/docker-or-podman", line 12, in <module>
    from typing import (
ImportError: cannot import name 'Literal'

I will remove the Literal from the script. To fix it you can remove the Literal import in /usr/local/bin/docker-or-podman on the VMs and replace the Literal["foo", "bar"] lines with an str.

**Comment by antarcticrainforest** [comment]
I've just checked, the main branch already doesn't have the Literal in  the docker-or-podman script. So the next release should be fixed. I am closing this issue.
